### ISSUE TITLE
Review Comments

### ISSUE THREAD

**Issue by Fawke** [shivamadurai/project-for-training-react#1]
1. Create a README.md file with few screenshots of the working demo and instructions to run and build the program.
2. Functionality check.
- [x] Sending and receiving messages on a channel - working.
- [ ] Sending and receiving direct messages - not implemented
- [ ] Creating multiple rooms - not implemented
- [ ] Authentication (Username and password) - not implemented
3. Code review
- [ ] Identify more actions and write reducers for them, currently only `GET_USER_NAME` and `SET_USER_NAME` present.
- [ ] Write and identify more sagas.
- [ ] Unit test cases missing for React components.
- [ ] Configure eslint with Airbnb rules and resolve all errors and warnings.
- [ ] Configure CI/CD

**Comment by shivamadurai** [comment]
Hi Neelan,

Done the review comments with CI settings

<img width="1629" alt="screen shot 2018-09-26 at 5 57 57 pm" src="https://user-images.githubusercontent.com/5967373/46079840-e335df00-c1b5-11e8-9295-532715fa9a95.png">

**Comment by Fawke** [comment]
**Funtionality Check**
1. Unable to create and add members to a private channel.

**[Bugs]**
1. On sending messages, the UI is flickering.
2. On creating a new channel, not able to send messages to that newly created channel.
3. The sent messages should auto scroll to the bottom.

**Comment by shivamadurai** [comment]
Funtionality Check

Unable to create and add members to a private channel. - Added functionality to add user to a Room. Click on the room and the member will be added into it.

[Bugs]

- On sending messages, the UI is flickering. - FIXED
- On creating a new channel, not able to send messages to that newly created channel. - FIXED. Message updating on specific channel
- The sent messages should auto scroll to the bottom. - FIXED

Kindly review my changes and approve it as completed.

**Comment by Fawke** [comment]
![screenshot from 2018-10-04 11-20-26](https://user-images.githubusercontent.com/14229985/46455237-bb530680-c7c7-11e8-97c5-3a1dabf6c315.png)
Unable to send message after logging in as a new user.

Still unable to create a private channel.
